Repository node-red-contrib-themes/theme-collection, pull requests merged in 2025-03, with the labels that each got.

#588 Check out the default branch when cloning
  lib/init.js
Labels: bugfix

#589 Add Zendesk Garden theme
  README.md
  src/themes/zendesk-garden/theme-custom.css
  src/themes/zendesk-garden/theme-mermaid.json
  src/themes/zendesk-garden/theme-monaco.json
  src/themes/zendesk-garden/theme.scss
Labels: new-theme

#592 Add quotes to allow path with spaces
  lib/dev.js
  lib/init.js
Labels: bugfix

#593 Fixes for running the dev environment on Windows
  lib/dev.js
  lib/init.js
Labels: bugfix

#594 Show a message if a step is taking too long
  lib/init.js
Labels: maintenance

#596 Small tweaks to the development documentation
  DEVELOPMENT.md
Labels: documentation
